# Generated by Django 4.1.4 on 2023-06-05 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_name', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='itempics')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
