# Generated by Django 4.1.4 on 2023-06-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
