# Generated by Django 4.1.4 on 2023-06-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_review_options_item_item_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.IntegerField(null=True),
        ),
    ]
