# Generated by Django 4.1.4 on 2023-06-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantiy',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
