# Generated by Django 4.1.4 on 2023-06-11 01:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_order_quantiy_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.CreateModel(
            name='Fullorder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('product_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fullorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.fullorder'),
        ),
    ]
