# Generated by Django 4.1.4 on 2023-06-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_customer_fullorder_order_fullorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullorder',
            old_name='product_order',
            new_name='product',
        ),
    ]
