# Generated by Django 4.1.4 on 2023-06-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_product_order_fullorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_order',
        ),
    ]
