# Generated by Django 4.1.4 on 2023-06-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_order_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullorder',
        ),
        migrations.AddField(
            model_name='fullorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
    ]
