# Generated by Django 4.1.4 on 2023-06-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
