# Generated by Django 4.1.4 on 2023-06-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_order_address_order_e_mail_order_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['firstname']},
        ),
    ]
